# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3c61101ac8372398459aa7d54d047400a896a152cddc370ce154f07b9ee42fc21a436251be669552d9e5534188d890a76b64fbbd23111e69a784df7eb3be23

test:
  secret_key_base: abd1ef3865b468f16b38fcf1351e70966c9eb4ed852298a7c37802770dde62fcaeac9ae0bdacf728c26202a0d9ac29251baf2b836c5c17cd295886a996c46ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
